# Generated by Django 6.0.2 on 2026-04-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('quantity', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/images')),
                ('bill', models.FileField(blank=True, null=True, upload_to='bill/')),
                ('register_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
